apiVersion: apps/v1
kind: Deployment
metadata:
  name: rallylite-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rallylite-frontend
  template:
    metadata:
      labels:
        app: rallylite-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/amirchaaari/rallylite-frontend:latest
          ports:
            - containerPort: 80