apiVersion: apps/v1
kind: Deployment
metadata:
  name: rallylite-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rallylite-backend
  template:
    metadata:
      labels:
        app: rallylite-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/amirchaaari/rallylite-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb+srv://amirchaari630:smrG8YWnVJkve8TK@cluster0.1ulxxgm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
---